mqtt:
  usuario: "your_username"
  contrasena: "your_password"
  url: "mqtt.example.com"
  puerto: 1883

devices:
  - ip: "192.168.1.1"
    name: "Router"
  - ip: "192.168.1.2"
    name: "NAS"
  - ip: "192.168.1.3"
    name: "Printer"

monitor:
  retry_attempts: 3
  retry_interval: 1.0
  iteration_interval: 60.0

cliente:
  id_cliente: PC_Test
  id_sbc: xd
  coordenadas:
    latitud: 9.929289
    longitud: -84.104287