mqtt:
  usuario: xd
  contrasena: xdddd
  url: idk
  puerto: 1883

devices:
  - ip: "192.168.0.34"
    name: "Server"
  - ip: "192.168.0.116"
    name: "Andres-PC"
  - ip: "192.168.0.26"
    name: "Printer"

monitor:
  retry_attempts: 3
  retry_interval: 20
  iteration_interval: 60.0

client:
  id_client: PC_Test
  id_sbc: xd